apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6IlFXNTBiMjVXYjJ4cmIzWTNNVHBuYVhSb2RXSmZjR0YwWHpFeFFVOVVNazVHU1RBME5XeFdVVXhGUVRRMU9HdGZXbEZNVFdReWIwcElkazQ1WW1GVmJXSlVlRW95UTNnM04xUXhUVWwxU21sMFpUbG5jRWhHZGxNd05WUkhWVEpEVFVWYVVWQkphRk5HVEU4PSIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVmYXVsdCIsCgkicGx1Z2lucyI6IHsKCQkiLXgtY2xpLWhpbnRzIjogewoJCQkiZW5hYmxlZCI6ICJ0cnVlIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
